Feature/assest
hedita/Acme-web-Solutions pull request #1
Opened 2022-01-16 17:18 UTC by hedita

2022-01-16 19:51 UTC, blacksrc commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,600;1,300&family=Roboto:wght@500;700&display=swap"
You have added both `Open Sans` and `Roboto` here. Please, remove `Roboto`. The easy way is to create the link from google fonts again. The final url should have `Open+Sans` as `family`.

2022-01-16 19:53 UTC, blacksrc commented on assets/css/general.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
Fix this as well. Check this comment https://github.com/hedita/Acme-web-Solutions/pull/1/files#r785486933

2022-01-17 08:58 UTC, hedita commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,600;1,300&family=Roboto:wght@500;700&display=swap"
Done.

2022-01-17 08:58 UTC, hedita commented on assets/css/general.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
Fixed.

2022-01-17 09:56 UTC, blacksrc requested changes

2022-01-17 09:56 UTC, blacksrc commented on assets/css/general.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
I cannot see any commit regarding to fixing this. Just to clarify this, you need to have the related font family only here. You are not using `Roboto`, etc. I added all `Open Sans` here but look at the `font-family`.
![image](https://user-images.githubusercontent.com/1394580/149747875-6d60b6f0-0ad0-4ebf-9d6f-773b28244324.png)

2022-01-17 09:57 UTC, blacksrc commented on assets/css/general.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
I cannot see any commit regarding to fixing this. Just to clarify this, you need to have the related font family only here. You are not using `Roboto`, etc. I added all `Open Sans` here but look at the `font-family`.

![image](https://user-images.githubusercontent.com/1394580/149748080-3ad6d74d-5321-495c-8c80-749903527418.png)

2022-01-17 10:43 UTC, merged